language: node_js
dist: trusty
addons:
  firefox: 58.0
  chrome: stable
node_js:
  - 6
  - 7
  - 8
  - 9
before_script:
  - npm install -g polymer-cli@1.6.0
  - npm install -g bower@1.8.4
  - bower install
script:
  - xvfb-run polymer test --verbose
